name: Build img branch
on:
  push:
    branches:
      - img
  workflow_dispatch:
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: img
          path: main
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build weasis-dicom-tools
        run: mvn -B clean install -f main
      - name: Checkout mvn-repo repository
        uses: actions/checkout@v2
        with:
          repository: nroduit/mvn-repo
          path: mvn-repo
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - name: Commit the maven packages
        run: |
          cd mvn-repo
          REPO=$(pwd)
          PKGFOLDER="org/weasis/weasis-dicom-tools"
          cd ~/.m2/repository/${PKGFOLDER}
          find . -name "*.jar" -o -name "*.pom" | cpio -updm ${REPO}/${PKGFOLDER}
          cd ${REPO}/${PKGFOLDER}
          IFS=$'\n'
          paths=($(find . -name "*.jar" -o -name "*.pom"))
          for file in ${paths[@]}; do
            $(sha1sum "${file}" | awk '{printf $1}' > "${file}".sha1)
            $(md5sum "${file}" | awk '{printf $1}' > "${file}".md5)
          done

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update weasis-dicom-tools"
          git push