name: Changelog
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Changelog Generator from github issues
        id: generate_changelog_file
        uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          compareLink: true
      - name: Git Auto Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: "Automatic changelog update"
          file_pattern: "CHANGELOG.md"
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          release_notes_file: CHANGELOG.md
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --notes '${{ steps.extract-release-notes.outputs.release_notes }}' --title ${{ github.ref_name }} ${{ github.ref_name }}