name: Changelog
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Changelog Generator from github issues
        id: generate_changelog_file
        uses: nroduit/changelog-generator-action@v2.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bugLabels: 'Type: Bug'
          enhancementLabels: 'Type: Enhancement,Type: Feature,Type: Security'
          issueLineLabels: 'Priority: Critical,Priority: High,Priority: Low,Priority: Medium,Type: Feature,Type: Security'
          excludeLabels: 'duplicate,question,invalid,wontfix,Type: Help Needed,Type: Idea,Type: Question,Status: Invalid,Status: Wontfix'
      - name: create commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic changelog update"
          file_pattern: "CHANGELOG.md"
      - name: Extract Release Notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}